export const GET_CATEGORY_MUSIC = 'GET_CATEGORY_MUSIC';
export const GET_CATEGORY_MUSIC_SUCCESS = 'GET_CATEGORY_MUSIC_SUCCESS';
export const GET_CATEGORY_MUSIC_FAIL = 'GET_CATEGORY_MUSIC_FAIL';
export const GET_CATEGORY_MUSIC_RESET = 'GET_CATEGORY_MUSIC_RESET'